language: ruby
rvm:
- 2.5.0
cache: bundler
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
- bundle exec rubocop app/views/* app/controllers/* app/models/* db/* spec/*
deploy:
  provider: heroku
  api_key:
    secure: H0cvIK+PPJdEAxP9YyOd9Lq3gyxtQEhxycF7TCerUJ3VzgY/dZjkxLTudoXhmhMLE72Fl3+w3C7WzWpxxyNRHMrMtrr89GC/NxAenpxq+h83P0QiTvLHjnX2dbh0e7DeomY4IL9T2HjSY+m39qlBdy4+bSQ/UNM3HTcXh3gyqoaZu/esYDyLM8/DMLmrkWzV4uMYscs1Z7F/WkDAEPJekgVzj/ZkZySE4wsgfbJ7mHgMIuVbb3BTBDKPM6K3E7Zpk94ut9t8kta3lCsEnUE5uA7PSeGG0Bkt/Jfu4DwSaVk8j/elOe9WG6rypIBEqZhgkIB9ridpwXhpE3IR+/2Ui6zxsopRmyqbup0MZXO9aqdbXsk/IgQDoaiuh0ghHxxuucn5u+juwmQ2nV2NCB4kvfuARJAUkUQ7d/0zcbM7l7ps4WtvtcGbB10EtHtpc5HOOQQM8iRCBCEEIbHdp+8pswsCQBPu7vtZcDopmx5YT9p8WL85fEe7g6Ps8UafolCfpBxLw0Vpjkj8FqumHHqO3xl0yGtGDAH3XBCpo/eKycR89L8b2AMYr87gtXSfPTDjSRiOn0Hed/Bv/P7aW3XRaTKtczXmw6Xbancbu95fnexQj4JsMXmuTwN2fjxjvJgxmjYw0X3bBSekDiFYtWv9m3JpJVu+F8LjkV3CBcgxGx4=
  app: ruby-acebook
  run:
    - "rails db:migrate"
